version: '3.8'

# services:
#   - type: web
#     name: django-app
#     env: python
#     buildCommand: |
#       pip install -r requirements.txt &&
#       python manage.py collectstatic --noinput &&
#       python manage.py migrate
#     startCommand: gunicorn project.wsgi:application
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.10.12
#       - key: DJANGO_SETTINGS_MODULE
#         value: myproject.settings

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=stockpilot
      - DB_USER=postgresql
      - DB_PASSWORD=S3NQZdP0PlUSJziutDi0FucqNB6NM4MM
      - DB_HOST=dpg-d0otvmeuk2gs7393ata0-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,yourdomain.com

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: stockpilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
