services:
  - type: web
    name: django-docker-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn myproject.wsgi:application"
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health/
    plan: starter # or free, standard, pro, pro plus
    
    # Auto-deploy from Git
    autoDeploy: true
    branch: main # or your main branch name
    
    # Environment variables
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: stockpilot-k51g.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: django-postgres-db
          property: connectionString
    
    # Disk storage for media files (optional)
    disk:
      name: django-media
      mountPath: /app/media
      sizeGB: 1

  # PostgreSQL Database
  - type: pserv
    name: django-postgres-db
    env: docker
    plan: starter
    image: postgres:15
    envVars:
      - key: POSTGRES_DB
        value: django_production
      - key: POSTGRES_USER
        value: django_user
      - key: POSTGRES_PASSWORD
        generateValue: true
    
    # Persistent storage for database
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10