# Generated by Django 5.1.3 on 2025-05-11 10:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_stockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='description',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
