# Generated by Django 4.2.7 on 2025-06-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_stockitem_description_stockitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagestats',
            name='logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='signups',
            field=models.IntegerField(default=0),
        ),
    ]
