# Generated by Django 4.2.7 on 2025-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_salesrecord_deletedrecordlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
